### ISSUE TITLE
Keeping having an issue with no backend available

### ISSUE THREAD

**Issue by lamemantis** [geftactics/python-StarTSPImage#6]
Sorry for the poor formatting im using my phone

Hello, i connected my TSP100III therm printer by usb and im running a simple script to see if my python program can find the printer.

The error im getting points back to:

usb.core.find(idVendor=vendorID, idProduct=productID)

In which the error says:

usb.core.NoBackendError: No backend available

im using the sample code provided and i just trimmed it to just test if it finds my printer. i confirmed the Ids in your sample are the same with my printer.

My question is: **Can you figure out why im getting this error? How can i resolve this? I could not find a single answer for this after searching for hours**

Import usb.core

VendorID = 0x0519
ProductID = 0x0003

dev =  usb.core.find(idVendor=vendorID, idProduct=productID)

if dev:
   print("FOUND")
else:
   print("NOT FOUND")

**Comment by geftactics** [comment]
I think you will be missing `libusb` from your system. Should be able to install with `brew install libusb` if on macOS

**Comment by lamemantis** [comment]
> I think you will be missing `libusb` from your system. Should be able to install with `brew install libusb` if on macOS

Maybe that could be the reason but now that ive installed it, did i need to to add anything else to the existing code? Ive added "import libusb"

I still get the same problem but im pretty sure i might need to do something to make use of the import. Im just clueless right now

**Comment by geftactics** [comment]
You only need to import usb.core

You should check the pyusb faq as your issue lies there rather than with this project I’m afraid…
https://github.com/pyusb/pyusb/blob/master/docs/faq.rst

you can also bypass the need for usb.core by sending to /dev/usb/lp0 (first example in the readme)

**Comment by lamemantis** [comment]
Thats understandable thank you for you help!
